package com.hs.eai.orderoverview.model;

// Generated 22-aug-2012 9:41:49 by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.NamedQueries;
import javax.persistence.NamedQuery;
import javax.persistence.OneToMany;
import javax.persistence.Table;

import org.hibernate.search.annotations.DocumentId;
import org.hibernate.search.annotations.Field;

import com.fasterxml.jackson.annotation.JsonIgnore;

/**
 * OrderHdr generated by hbm2java
 */
@Entity
@Table(name="ORDER_HDR")
@NamedQueries({
	@NamedQuery(name = "OrderHdr.findAll", query = "SELECT o FROM OrderHdr o"),
	@NamedQuery(name = "OrderHdr.findByName", query = "SELECT o FROM OrderHdr o where o.name=:name"),
	@NamedQuery(name = "OrderHdr.findByShipTo", query = "SELECT o FROM OrderHdr o where o.shipto=:shipto"),
	@NamedQuery(name = "OrderHdr.findByOrganization", query = "SELECT o FROM OrderHdr o where o.salesOrganizationId=:salesOrganizationId"),
	@NamedQuery(name = "OrderHdr.findByBillTo", query = "SELECT o FROM OrderHdr o where o.billto=:billto"),
	
})
public class OrderHdr implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -5204916092936772401L;

	@Id
	@GeneratedValue(strategy=GenerationType.AUTO)
	@DocumentId
	@Column(name="ID",columnDefinition="numeric")
	private Integer id;
	
	@ManyToOne
	//@JoinColumn(name = "order_status_id" ,nullable=false)
	private OrderStatus orderStatus;
	@Column(name="company_code_id")
	private Integer companyCodeId;
	
	@Field
	private String refno;
	@Field
	private Integer shipto;
	@Field
	private Integer billto;
	@Column(name="country_id")
	@Field
	private Integer countryId;
	@Column(name="system_source_id")
	private Integer systemSourceId;
	@Column(name="system_destination_id")
	private Integer systemDestinationId;
	
	@Field
	@Column(name="order_date" ,columnDefinition="timestamp")
	private Date orderDate;
	@Field
	@Column(name="data_sent" ,columnDefinition="timestamp")
	private Date dataSent;
	
	@Column(name="order_confirmation")
	private java.lang.Boolean orderConfirmation;
	@Column(name="shipment_confirmation")
	private java.lang.Boolean shipmentConfirmation;
	@Column(name="email_address")
	@Field
	private String emailAddress;
	@Column(name="sales_organization_id")
	@Field
	private Integer salesOrganizationId;
	@Field
	private String name;
	
	@Column(name="date_created" ,columnDefinition="timestamp")
	private Date dateCreated;
	
	@Column(name="date_updated" ,columnDefinition="timestamp")
	private Date dateUpdated;
	
	@OneToMany(mappedBy="orderHdr")
	//@JoinColumn(name = "order_hdr_id")
	@JsonIgnore
	private Set<OrderDetail> orderDetails = new HashSet<OrderDetail>();
	@Column(name="user_id")
	private String userId;
	@Column(name="ogone_payment_id")
	private String ogonePaymentId;
	
	@Column(name="order_email_address")
	private String orderEmailConf;
	@Column(name="shipment_email_address")
	private String shipEmailConf;
	
	@Column(name="order_comment")
	private String orderComment;

	@Column(name="customer_order_reference")
	private String customerOrderReference;
	@Column(name="shipping_method")
	private String shippingMethod;
	@Column(name="payment_method")
	private String paymentMethod;
	@Column(name="promo_code")
	private String promoCode;
	
	public OrderHdr() {
	}

	public OrderHdr(Integer id, OrderStatus orderStatus, Date orderRecieved, java.lang.Boolean orderConfirmation, java.lang.Boolean shipmentConfirmation) {
		this.id = id;
		this.orderStatus = orderStatus;
		this.dataSent = orderRecieved;
		this.orderConfirmation = orderConfirmation;
		this.shipmentConfirmation = shipmentConfirmation;
	}

	public OrderHdr(Integer id, OrderStatus orderStatus, Integer companyCode, String refno, Integer shipto, Integer billto, Date orderDate, Date orderRecieved, java.lang.Boolean orderConfirmation, java.lang.Boolean shipmentConfirmation, String emailAddress, Set <OrderDetail>orderDetails, String ogonePaymentId, String orderEmailConf, String shipEmailConf, String orderComment, String customerOrderReference, String shippingMethod, String paymentMethod, String promoCode) {
		this.id = id;
		this.orderStatus = orderStatus;
		this.companyCodeId = companyCode;
		this.refno = refno;
		this.shipto = shipto;
		this.billto = billto;
		this.orderDate = orderDate;
		this.dataSent = orderRecieved;
		this.orderConfirmation = orderConfirmation;
		this.shipmentConfirmation = shipmentConfirmation;
		this.emailAddress = emailAddress;
		this.orderDetails = orderDetails;
		this.ogonePaymentId = ogonePaymentId;
		this.orderEmailConf = orderEmailConf;
		this.shipEmailConf = shipEmailConf;
		this.orderComment = orderComment;
		this.customerOrderReference = customerOrderReference;
		this.shippingMethod = shippingMethod;
		this.paymentMethod = paymentMethod;
		this.promoCode = promoCode;
	}

	public String getPaymentMethod() {
		return paymentMethod;
	}

	public void setPaymentMethod(String shippingMethod) {
		this.paymentMethod = shippingMethod;
	}

	public String getShippingMethod() {
		return shippingMethod;
	}

	public void setShippingMethod(String shippingMethod) {
		this.shippingMethod = shippingMethod;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getUserId() {
		return userId;
	}

	public void setUserId(String userId) {
		this.userId = userId;
	}

	public OrderStatus getOrderStatus() {
		return this.orderStatus;
	}

	public void setOrderStatus(OrderStatus orderStatus) {
		this.orderStatus = orderStatus;
	}

	public Integer getCompanyCodeId() {
		return this.companyCodeId;
	}

	public void setCompanyCodeId(Integer companyCodeId) {
		this.companyCodeId = companyCodeId;
	}

	public String getRefno() {
		return this.refno;
	}

	public void setRefno(String refno) {
		this.refno = refno;
	}

	public Integer getShipto() {
		return this.shipto;
	}

	public void setShipto(Integer shipto) {
		this.shipto = shipto;
	}

	public Integer getBillto() {
		return this.billto;
	}

	public void setBillto(Integer billto) {
		this.billto = billto;
	}

	public Date getOrderDate() {
		return this.orderDate;
	}

	public void setOrderDate(Date orderDate) {
		this.orderDate = orderDate;
	}
	
	public Date getDataSent() {
		return dataSent;
	}

	public void setDataSent(Date dataSent) {
		this.dataSent = dataSent;
	}

	public java.lang.Boolean getOrderConfirmation() {
		return this.orderConfirmation;
	}

	public void setOrderConfirmation(java.lang.Boolean orderConfirmation) {
		this.orderConfirmation = orderConfirmation;
	}

	public java.lang.Boolean getShipmentConfirmation() {
		return this.shipmentConfirmation;
	}

	public void setShipmentConfirmation(java.lang.Boolean shipmentConfirmation) {
		this.shipmentConfirmation = shipmentConfirmation;
	}

	public String getEmailAddress() {
		return this.emailAddress;
	}

	public void setEmailAddress(String emailAddress) {
		this.emailAddress = emailAddress;
	}

	public Set<OrderDetail> getOrderDetails() {
		return this.orderDetails;
	}

	public void setOrderDetails(Set<OrderDetail> orderDetails) {
		this.orderDetails = orderDetails;
	}

	public Date getDateCreated() {
		return dateCreated;
	}

	public void setDateCreated(Date dateCreated) {
		this.dateCreated = dateCreated;
	}

	public Date getDateUpdated() {
		return dateUpdated;
	}

	public void setDateUpdated(Date dateUpdated) {
		this.dateUpdated = dateUpdated;
	}

	public Integer getCountryId() {
		return countryId;
	}

	public void setCountryId(Integer countryId) {
		this.countryId = countryId;
	}

	public Integer getSystemSourceId() {
		return systemSourceId;
	}

	public void setSystemSourceId(Integer systemSourceId) {
		this.systemSourceId = systemSourceId;
	}

	public Integer getSystemDestinationId() {
		return systemDestinationId;
	}

	public void setSystemDestinationId(Integer systemDestinationId) {
		this.systemDestinationId = systemDestinationId;
	}

	public Integer getSalesOrganizationId() {
		return salesOrganizationId;
	}

	public void setSalesOrganizationId(Integer salesOrganizationId) {
		this.salesOrganizationId = salesOrganizationId;
	}

	public String getName() {
		return name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getOgonePaymentId() {
		return ogonePaymentId;
	}

	public void setOgonePaymentId(String paymentId) {
		this.ogonePaymentId = paymentId;
	}

	public String getOrderEmailConf() {
		return orderEmailConf;
	}

	public void setOrderEmailConf(String orderEmailConf) {
		this.orderEmailConf = orderEmailConf;
	}

	public String getShipEmailConf() {
		return shipEmailConf;
	}

	public void setShipEmailConf(String shipEmailConf) {
		this.shipEmailConf = shipEmailConf;
	}
	
	public String getOrderComment() {
		return this.orderComment;
	}

	public void setOrderComment(String orderComment) {
		this.orderComment = orderComment;
	}

	public String getCustomerOrderReference() {
		return customerOrderReference;
	}

	public void setCustomerOrderReference(String customerOrderReference) {
		this.customerOrderReference = customerOrderReference;
	}

	public String getPromoCode() {
		return promoCode;
	}

	public void setPromoCode(String promoCode) {
		this.promoCode = promoCode;
	}
}