package com.hs.eai.orderoverview.model;

// Generated 22-aug-2012 9:41:49 by Hibernate Tools 3.4.0.CR1

import java.io.Serializable;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

import org.hibernate.search.annotations.DocumentId;

/**
 * OrderStatus generated by hbm2java
 */
@Entity
@Table(name="ORDER_STATUS")
public class OrderStatus implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -5088831468358766917L;
	@Id
	@GeneratedValue(strategy=GenerationType.AUTO)
	@DocumentId
	@Column(name="ID",columnDefinition="numeric")
	private Integer id;
	private String code;
	private String description;
	@OneToMany
	@JoinColumn(name = "order_status_id" ,nullable=false)
	private Set<OrderHdr> orderHdrs = new HashSet<OrderHdr>();

	public OrderStatus() {
	}

	public OrderStatus(Integer id, String code, String description) {
		this.id = id;
		this.code = code;
		this.description = description;
	}

	public OrderStatus(Integer id, String code, String description, Set<OrderHdr> orderHdrs) {
		this.id = id;
		this.code = code;
		this.description = description;
		this.orderHdrs = orderHdrs;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getCode() {
		return this.code;
	}

	public void setCode(String code) {
		this.code = code;
	}

	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	public Set<OrderHdr> getOrderHdrs() {
		return this.orderHdrs;
	}

	public void setOrderHdrs(Set<OrderHdr> orderHdrs) {
		this.orderHdrs = orderHdrs;
	}

}
