package com.hs.eai.orderoverview.model;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.NamedQueries;
import javax.persistence.NamedQuery;
import javax.persistence.Table;

import org.hibernate.search.annotations.DocumentId;

// Generated 22-aug-2012 9:41:49 by Hibernate Tools 3.4.0.CR1


/**
 * OrderDetail generated by hbm2java
 */
@Entity
@Table(name="ORDER_DETAIL")
@NamedQueries({
	@NamedQuery(name = "OrderDetail.findAll", query = "SELECT o FROM OrderDetail o"),
	@NamedQuery(name = "OrderDetail.findByOrderHdrId", query = "SELECT o FROM OrderDetail o where o.orderHdr=:orderHdr")
	
})
public class OrderDetail implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	@Id
	@GeneratedValue(strategy=GenerationType.AUTO)
	@DocumentId
	@Column(name="ID",columnDefinition="numeric")
	private Integer id;
	@ManyToOne
	@JoinColumn(name = "order_hdr_id" ,nullable=false)
	private OrderHdr orderHdr;
	private String itemcode;
	private Integer quantity;
	private String uom;
	private Double unitprice;
	@Column(name="line_item_id")
	private Integer lineItemId;
	@Column(name="invoice_type")
	private String invoiceType;
	@Column(name="promo_code")
	private String promoCode;
	
	public OrderDetail() {
	}

	public OrderDetail(Integer id, OrderHdr orderHdr, String itemcode, Integer quantity, Double unitprice) {
		this.id = id;
		this.orderHdr = orderHdr;
		this.itemcode = itemcode;
		this.quantity = quantity;
		this.unitprice = unitprice;
	}

	public OrderDetail(Integer id, OrderHdr orderHdr, Integer lineItemId, String itemcode, Integer quantity, String uom, Double unitprice) {
		this.id = id;
		this.orderHdr = orderHdr;
		this.lineItemId = lineItemId;
		this.itemcode = itemcode;
		this.quantity = quantity;
		this.uom = uom;
		this.unitprice = unitprice;
	}
	
	public Integer getLineItemId() {
		return lineItemId;
	}

	public void setLineItemId(Integer lineItemId) {
		this.lineItemId = lineItemId;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public OrderHdr getOrderHdr() {
		return this.orderHdr;
	}

	public void setOrderHdr(OrderHdr orderHdr) {
		this.orderHdr = orderHdr;
	}

	public String getItemcode() {
		return this.itemcode;
	}

	public void setItemcode(String itemcode) {
		this.itemcode = itemcode;
	}

	public Integer getQuantity() {
		return this.quantity;
	}

	public void setQuantity(Integer quantity) {
		this.quantity = quantity;
	}

	public String getUom() {
		return this.uom;
	}

	public void setUom(String uom) {
		this.uom = uom;
	}

	public Double getUnitprice() {
		return this.unitprice;
	}

	public void setUnitprice(Double unitprice) {
		this.unitprice = unitprice;
	}

	public String getInvoiceType() {
		return this.invoiceType;
	}

	public void setInvoiceType(String invoiceType) {
		this.invoiceType = invoiceType;
	}

	public String getPromoCode() {
		return this.promoCode;
	}

	public void setPromoCode(String promoCode) {
		this.promoCode = promoCode;
	}

}
