package com.hs.eai.orderoverview.model;

// Generated 14-nov-2014 11:58:10 by Hibernate Tools 3.4.0.CR1


/**
 * OrderDetailFreeGood generated by hbm2java
 */
@SuppressWarnings("serial")
public class OrderDetailFreeGood implements java.io.Serializable {

	private int id;
	private int orderDetailId;
	private String itemCode;
	private int quantity;
	private String type;

	public OrderDetailFreeGood() {
	}

	public OrderDetailFreeGood(int id, int orderDetailId,
			String itemCode, int quantity, String type) {
		this.id = id;
		this.orderDetailId = orderDetailId;
		this.itemCode = itemCode;
		this.quantity = quantity;
		this.setType(type);
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public int getOrderDetailId() {
		return this.orderDetailId;
	}

	public void setOrderDetailId(int orderDetailId) {
		this.orderDetailId = orderDetailId;
	}

	public String getItemCode() {
		return this.itemCode;
	}

	public void setItemCode(String itemCode) {
		this.itemCode = itemCode;
	}

	public int getQuantity() {
		return this.quantity;
	}

	public void setQuantity(int quantity) {
		this.quantity = quantity;
	}

	/**
	 * @return the type
	 */
	public String getType() {
		return type;
	}

	/**
	 * @param type the type to set
	 */
	public void setType(String type) {
		this.type = type;
	}

}
